'/franchises/search':
  get:
    tags: [Franchise]
    summary: Search franchises
    operationId: searchFranchises
    parameters:
      - name: name
        in: query
        description: Partial name of the franchise to look for
        required: true
        schema:
          type: string
    responses:
      '200':
        description: List of matching franchises
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Franchise'

'/franchises':
  get:
    tags: [Franchise]
    summary: Get all franchises
    operationId: getAllFranchises
    responses:
      '200':
        description: List of all franchises
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Franchise'
  post:
    tags: [Franchise]
    summary: Create a new franchise
    operationId: createFranchise
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                minLength: 3
                maxLength: 100
                description: Name of the franchise
              games:
                type: array
                description: Array of **game IDs** to associate with this franchis.
                items:
                  type: integer
            example:
              name: 'Super Mario'
    responses:
      '201':
        description: Franchise created successfully
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - properties:
                    data:
                      $ref: '#/components/schemas/Franchise'
      '400':
        description: Bad request - Invalid input data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponse'

'/franchises/{id}':
  get:
    tags: [Franchise]
    summary: Get a franchise by ID
    operationId: getFranchiseById
    parameters:
      - name: id
        in: path
        required: true
        description: The franchise ID
        schema:
          type: integer
          format: int64
    responses:
      '200':
        description: Franchise found
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - properties:
                    data:
                      $ref: '#/components/schemas/Franchise'
      '404':
        description: Franchise not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponseError'
  put:
    tags: [Franchise]
    summary: Update a franchise completely
    operationId: updateFranchise
    parameters:
      - name: id
        in: path
        required: true
        description: The franchise ID
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                minLength: 3
                maxLength: 100
                description: Name of the franchise
              games:
                type: array
                items:
                  type: integer
                description: Array of game IDs to associate with this franchise
            example:
              name: 'Super Mario'
              games: [1, 2, 3]
    responses:
      '200':
        description: Franchise updated successfully
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - properties:
                    data:
                      $ref: '#/components/schemas/Franchise'
      '400':
        description: Bad request - Invalid input data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponseError'
      '404':
        description: Franchise not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponseError'
  patch:
    tags: [Franchise]
    summary: Partially update a franchise
    operationId: partialUpdateFranchise
    parameters:
      - name: id
        in: path
        required: true
        description: The franchise ID
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                minLength: 3
                maxLength: 100
                description: Name of the franchise
              games:
                type: array
                items:
                  type: integer
                description: Array of game IDs to associate with this franchise
            example:
              name: 'Super Mario Bros'
    responses:
      '200':
        description: Franchise updated successfully
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - properties:
                    data:
                      $ref: '#/components/schemas/Franchise'
      '400':
        description: Bad request - Invalid input data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponseError'
      '404':
        description: Franchise not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponseError'
  delete:
    tags: [Franchise]
    summary: Delete a franchise
    operationId: deleteFranchise
    parameters:
      - name: id
        in: path
        required: true
        description: The franchise ID
        schema:
          type: integer
          format: int64
    responses:
      '200':
        description: Franchise deleted successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponse'
      '404':
        description: Franchise not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponseError'
