GET http://localhost:8080/api/tags/


### obtener un tag
GET http://localhost:8080/api/tags/5


### crear un nuevo tag
POST http://localhost:8080/api/tags
Content-Type: application/json

{
  "name": "Sci Fi",
  "description": "Ships and planets"
  
}

### borrar un tag
DELETE http://localhost:8080/api/tags/5

###
PUT  http://localhost:8080/api/tags/5
Content-Type: application/json

{
  "name": "Studio Skibidi",
  "description": "Cosos"
 
}

###
PATCH http://localhost:8080/api/tags/6
Content-Type: application/json

{
  "tags" : [6]
}
