### Reiniciar server
POST http://localhost:8080/restart

###
GET http://localhost:8080/api/platforms

###
POST http://localhost:8080/api/platforms
Content-Type: application/json

{
  "name": "Studio",
  "type": ["Developer", "asldkfjaslñdkfj"],
  "site": "https://google.com"
}

###
GET http://localhost:8080/api/platforms/1

###
PUT http://localhost:8080/api/platforms/4
Content-Type: application/json

{
  "name": "Studio Skibidi",
  "type": ["Publisher"],
  "site": "https://coso.org"
}

###
PATCH http://localhost:8080/api/platforms/4
Content-Type: application/json

{
  "name": "test patched"
}


###
DELETE http://localhost:8080/api/platforms/1