### Reiniciar server
POST http://localhost:8080/restart

###
GET http://localhost:8080/api/platforms/

###
POST http://localhost:8080/api/platforms
Content-Type: application/json

{
  "name": "PlayStation1",
  "img": "imgPS1"
}


#@id = {{createPlatform.response.body.data.id}}
###
GET http://localhost:8080/api/platforms/1

###
PUT http://localhost:8080/api/platforms/4
Content-Type: application/json

{
  "name": "PlayStation1",
  "img": "imgPS1"
}

###


PATCH http://localhost:8080/api/platforms/4
Content-Type: application/json

{
  "name": "test patched"
}


###
DELETE http://localhost:8080/api/platforms/1